import React, { useState, useEffect } from 'react';
import { authService } from '../services/authService';
import { analysisService } from '../services/analysisService';
import { aiService } from '../services/aiService';
import { useLocation } from 'react-router-dom';
import './LearningPath.css';

const priorityConfig = {
  HIGH: { color: '#ef4444', label: 'High Priority', icon: '🔴' },
  MEDIUM: { color: '#f59e0b', label: 'Medium Priority', icon: '🟡' },
  LOW: { color: '#10b981', label: 'Low Priority', icon: '🟢' },
};

const LearningPath = () => {
  const user = authService.getCurrentUser();
  const location = useLocation();
  const [roles, setRoles] = useState([]);
  const [selectedRole, setSelectedRole] = useState(location.state?.roleId || '');
  const [learningPath, setLearningPath] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    loadRoles();
    if (location.state?.autoGenerate && location.state?.roleId) {
      // Small delay to ensure roles exist or just trigger generation directly
      setTimeout(() => handleGenerate(location.state.roleId), 500);
    }
  }, []);

  const loadRoles = async () => {
    try {
      const rolesData = await analysisService.getAllRoles();
      setRoles(rolesData);
    } catch (err) {
      console.error('Error loading roles:', err);
    }
  };

  const handleGenerate = async (roleIdOverride = null) => {
    const targetRoleId = roleIdOverride || selectedRole;
    if (!targetRoleId) {
      setError('Please select a target role');
      return;
    }

    setLoading(true);
    setError('');
    setLearningPath(null);

    try {
      const result = await aiService.generateLearningPath(user.userId, targetRoleId);
      setLearningPath(result);
    } catch (err) {
      setError('Failed to generate learning path. Please try again.');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="lp-page">
      {/* Background effects */}
      <div className="lp-bg">
        <div className="lp-orb lp-orb-1"></div>
        <div className="lp-orb lp-orb-2"></div>
      </div>

      <div className="lp-container">
        {/* Header */}
        <section className="lp-header fade-in">
          <div className="lp-header-badge">🤖 Powered by Google Gemini AI</div>
          <h1>AI Learning <span className="lp-gradient-text">Path Generator</span></h1>
          <p>Get a personalized, step-by-step roadmap to reach your dream role — generated by AI based on your actual skill gaps.</p>
        </section>

        {/* Role Selector */}
        <section className="lp-selector fade-in">
          <div className="lp-selector-card">
            <h2>Select Your Target Role</h2>
            <div className="lp-selector-row">
              <select
                value={selectedRole}
                onChange={(e) => { setSelectedRole(e.target.value); setError(''); }}
              >
                <option value="">Choose a role...</option>
                {roles.map((role) => (
                  <option key={role.id} value={role.id}>{role.name}</option>
                ))}
              </select>
              <button
                className="lp-generate-btn"
                onClick={handleGenerate}
                disabled={loading || !selectedRole}
              >
                {loading ? (
                  <>
                    <span className="lp-spinner"></span>
                    Generating with AI...
                  </>
                ) : (
                  <>✨ Generate AI Path</>
                )}
              </button>
            </div>
            {error && <p className="lp-error">{error}</p>}
          </div>
        </section>

        {/* Loading State */}
        {loading && (
          <section className="lp-loading-state fade-in">
            <div className="lp-ai-loader">
              <div className="lp-ai-pulse"></div>
              <div className="lp-ai-icon">🤖</div>
            </div>
            <h3>AI is analyzing your skills...</h3>
            <p>Gemini is crafting a personalized learning roadmap just for you. This may take a few seconds.</p>
            <div className="lp-loading-steps">
              <div className="lp-loading-step active">
                <span className="lp-ls-dot"></span> Analyzing skill gaps
              </div>
              <div className="lp-loading-step active" style={{ animationDelay: '1s' }}>
                <span className="lp-ls-dot"></span> Generating learning steps
              </div>
              <div className="lp-loading-step active" style={{ animationDelay: '2s' }}>
                <span className="lp-ls-dot"></span> Finding best resources
              </div>
            </div>
          </section>
        )}

        {/* Results */}
        {learningPath && !loading && (
          <div className="lp-results fade-in">
            {/* Overview Card */}
            <section className="lp-overview-card">
              <div className="lp-overview-header">
                <div>
                  <h2>🎯 Learning Path for {learningPath.roleName}</h2>
                  <p className="lp-overview-text">{learningPath.overview}</p>
                </div>
                <div className="lp-overview-stat">
                  <span className="lp-overview-num">{learningPath.totalEstimatedWeeks}</span>
                  <span className="lp-overview-label">Estimated Weeks</span>
                </div>
              </div>
              <div className="lp-overview-meta">
                <span>📚 {learningPath.learningSteps?.length || 0} Steps</span>
                <span>⏱️ ~{learningPath.totalEstimatedWeeks} Weeks</span>
                <span>🤖 AI Generated</span>
              </div>
            </section>

            {/* Timeline */}
            <section className="lp-timeline">
              {learningPath.learningSteps?.map((step, index) => {
                const priority = priorityConfig[step.priority] || priorityConfig.MEDIUM;
                return (
                  <div key={index} className="lp-step-card" style={{ '--step-delay': `${index * 0.1}s` }}>
                    <div className="lp-step-timeline">
                      <div className="lp-step-number" style={{ background: priority.color }}>
                        {step.stepNumber}
                      </div>
                      {index < learningPath.learningSteps.length - 1 && (
                        <div className="lp-step-line"></div>
                      )}
                    </div>
                    <div className="lp-step-content">
                      <div className="lp-step-header">
                        <h3>{step.title}</h3>
                        <div className="lp-step-badges">
                          <span className="lp-badge lp-badge-duration">⏱️ {step.duration}</span>
                          <span className="lp-badge" style={{ background: priority.color + '20', color: priority.color, borderColor: priority.color + '40' }}>
                            {priority.icon} {priority.label}
                          </span>
                        </div>
                      </div>
                      <p className="lp-step-desc">{step.description}</p>
                      {step.resources && step.resources.length > 0 && (
                        <div className="lp-step-resources">
                          <h4>📖 Resources</h4>
                          <ul>
                            {step.resources.map((resource, rIdx) => (
                              <li key={rIdx}>{resource}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </section>

            {/* Regenerate */}
            <section className="lp-regen">
              <button className="lp-generate-btn" onClick={handleGenerate}>
                🔄 Regenerate Path
              </button>
              <p>Not happy with the path? Generate a new one — each result is unique!</p>
            </section>
          </div>
        )}
      </div>
    </div>
  );
};

export default LearningPath;
