server.port=8080
spring.application.name=skill-gap-analysis

spring.datasource.url=jdbc:postgresql://localhost:5432/skillgap_db
spring.datasource.username=postgres
spring.datasource.password=my@62post67
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

# Show SQL (dev only)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: Better Hibernate debugging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.sql.init.mode=never


jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000


logging.level.com.skillgap=DEBUG
logging.level.org.springframework.security=DEBUG

# Gemini AI Configuration
# Gemini AI Configuration
gemini.api.key=AIzaSyBeJenOHR2pV-l-bSNMEl0BlmZEhxFAbC4
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Google OAuth Configuration
google.client.id=761922897385-p50c29bt4g26dk43fuiaou93kaegp01c.apps.googleusercontent.com