server.port=8080
spring.application.name=skill-gap-analysis

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

# Show SQL (dev only)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: Better Hibernate debugging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.sql.init.mode=never


jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


logging.level.com.skillgap=DEBUG
logging.level.org.springframework.security=DEBUG

# Gemini AI Configuration
# Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Google OAuth Configuration
google.client.id=${GOOGLE_CLIENT_ID}